org:
  name: cbdc-pilot
  domain: cbdc.cluster.local

besu:
  chainId: 1337
  nodeCount: 1
  imageTag: latest
  baseNodePort: 31545
  blockPeriod: 2
  zeroBaseFee: true
  evmFork: cancun

paladin:
  imageTag: latest
  baseNodePort: 31548
  domains:
    noto: true
    zeto: false
    pente: true
